package com.demo.justworktimer.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF5652b2)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFe3dfff)
val md_theme_light_onPrimaryContainer = Color(0xFF0d006b)
val md_theme_light_secondary = Color(0xFF5e5c72)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe3dff9)
val md_theme_light_onSecondaryContainer = Color(0xFF1a1a2c)
val md_theme_light_tertiary = Color(0xFF7a5368)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd8eb)
val md_theme_light_onTertiaryContainer = Color(0xFF2f1123)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffbff)
val md_theme_light_onBackground = Color(0xFF1c1b1f)
val md_theme_light_surface = Color(0xFFfffbff)
val md_theme_light_onSurface = Color(0xFF1c1b1f)
val md_theme_light_surfaceVariant = Color(0xFFe5e1ec)
val md_theme_light_onSurfaceVariant = Color(0xFF47464f)
val md_theme_light_outline = Color(0xFF787680)
val md_theme_light_inverseOnSurface = Color(0xFFf3eff4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFFc4c0ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFc4c0ff)
val md_theme_dark_onPrimary = Color(0xFF271f82)
val md_theme_dark_primaryContainer = Color(0xFF3e3999)
val md_theme_dark_onPrimaryContainer = Color(0xFFe3dfff)
val md_theme_dark_secondary = Color(0xFFc7c4dd)
val md_theme_dark_onSecondary = Color(0xFF2f2e42)
val md_theme_dark_secondaryContainer = Color(0xFF464559)
val md_theme_dark_onSecondaryContainer = Color(0xFFe3dff9)
val md_theme_dark_tertiary = Color(0xFFeab9d1)
val md_theme_dark_onTertiary = Color(0xFF472639)
val md_theme_dark_tertiaryContainer = Color(0xFF603c50)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd8eb)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1c1b1f)
val md_theme_dark_onBackground = Color(0xFFe5e1e6)
val md_theme_dark_surface = Color(0xFF1c1b1f)
val md_theme_dark_onSurface = Color(0xFFe5e1e6)
val md_theme_dark_surfaceVariant = Color(0xFF47464f)
val md_theme_dark_onSurfaceVariant = Color(0xFFc8c5d0)
val md_theme_dark_outline = Color(0xFF928f9a)
val md_theme_dark_inverseOnSurface = Color(0xFF1c1b1f)
val md_theme_dark_inverseSurface = Color(0xFFe5e1e6)
val md_theme_dark_inversePrimary = Color(0xFF5652b2)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF5652b2)
val error = Color(0xFFba1b1b)
val Custom0 = Color(0xFFA1BE0C)
